irods-rest:
  image: km4rcus/irods-rest:4.0.2.5-rc1
  ports:
   - "8080:8080"
  links:
   - irods

irods:
  image: km4rcus/icat:4.1.8 
  container_name: irods
  ports:
   - "1247:1247"
  hostname: irods
  command: irods
  links:
    - irods-db
  environment:
    RODS_PASSWORD: irods
    PGPASSWORD: foobar
  volumes:
    - icat_config:/etc/irods 
    - vault:/mnt/cmcc_vault

irods-db:
  image: postgres:9.4
  environment:
    POSTGRES_PASSWORD: foobar
  volumes:
    - icat_db:/var/lib/postgresql
